import { existsSync, writeFileSync, mkdirSync, readFileSync } from "fs"
import { join, dirname } from "path"
import chalk from "chalk"

// Component registry — maps component names to their source locations
const REGISTRY: Record<string, { file: string; deps?: string[] }> = {
  card: { file: "card.tsx" },
  table: { file: "table.tsx" },
  "code-block": { file: "code-block.tsx", deps: ["react-syntax-highlighter"] },
  "markdown-view": { file: "markdown-view.tsx", deps: ["react-markdown", "remark-gfm"] },
  "image-view": { file: "image-view.tsx" },
  alert: { file: "alert.tsx" },
  badge: { file: "badge.tsx" },
  tabs: { file: "tabs.tsx" },
  accordion: { file: "accordion.tsx" },
  "stat-card": { file: "stat-card.tsx" },
  "stats-grid": { file: "stats-grid.tsx" },
  "bar-chart": { file: "bar-chart.tsx", deps: ["recharts"] },
  "line-chart": { file: "line-chart.tsx", deps: ["recharts"] },
  "pie-chart": { file: "pie-chart.tsx", deps: ["recharts"] },
  "progress-bar": { file: "progress-bar.tsx" },
  "kpi-card": { file: "kpi-card.tsx" },
  avatar: { file: "avatar.tsx" },
  divider: { file: "divider.tsx" },
  skeleton: { file: "skeleton.tsx" },
}

const AVAILABLE = Object.keys(REGISTRY)

export async function add(
  components: string[] | undefined,
  options: { all?: boolean; overwrite?: boolean; cwd?: string }
) {
  const cwd = options.cwd ?? process.cwd()

  // Load config
  const configPath = join(cwd, "fabrik.config.ts")
  let componentsDir = "components/fabrik"

  if (existsSync(configPath)) {
    const configContent = readFileSync(configPath, "utf-8")
    const match = configContent.match(/componentsDir:\s*"([^"]+)"/)
    if (match?.[1]) componentsDir = match[1]
  }

  // Determine which components to add
  const toAdd = options.all ? AVAILABLE : (components ?? [])

  if (toAdd.length === 0) {
    console.log(chalk.yellow("\n  No components specified."))
    console.log("  Available:", AVAILABLE.join(", "))
    console.log(chalk.dim("  Use --all to add all components\n"))
    return
  }

  // Validate component names
  const invalid = toAdd.filter((c) => !REGISTRY[c])
  if (invalid.length > 0) {
    console.log(chalk.red(`\n  Unknown components: ${invalid.join(", ")}`))
    console.log("  Available:", AVAILABLE.join(", "))
    return
  }

  console.log(chalk.bold("\n  Adding components...\n"))

  const allDeps = new Set<string>()
  let added = 0

  for (const name of toAdd) {
    const entry = REGISTRY[name]!
    const targetDir = join(cwd, componentsDir)
    const targetPath = join(targetDir, entry.file)

    // Check if file exists
    if (existsSync(targetPath) && !options.overwrite) {
      console.log(chalk.dim(`  - ${entry.file} (exists, skip)`))
      continue
    }

    // Create directory
    mkdirSync(dirname(targetPath), { recursive: true })

    // Write a placeholder component file
    // In a real CLI, this would fetch from a registry or copy from templates
    const content = generateComponentSource(name)
    writeFileSync(targetPath, content)
    console.log(chalk.green("  ✓"), `${entry.file} → ${componentsDir}/${entry.file}`)
    added++

    // Collect deps
    if (entry.deps) {
      for (const dep of entry.deps) allDeps.add(dep)
    }
  }

  // Report
  if (added === 0) {
    console.log(chalk.dim("\n  No new components added.\n"))
    return
  }

  console.log(chalk.green(`\n  ✓ Added ${added} component${added > 1 ? "s" : ""}`))

  if (allDeps.size > 0) {
    console.log(chalk.dim(`\n  Install additional dependencies:`))
    console.log(chalk.dim(`    pnpm add ${[...allDeps].join(" ")}\n`))
  } else {
    console.log()
  }
}

function generateComponentSource(name: string): string {
  const componentName = name
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("")

  return `"use client"

import { defineComponent } from "@fabrik/ui"
import { z } from "zod"

// TODO: Implement ${componentName} component
// This is a placeholder generated by \`fabrik add ${name}\`
// Replace with your implementation

const schema = z.object({
  // Define your props here
})

function ${componentName}Renderer(props: z.infer<typeof schema>) {
  return (
    <div className="rounded-xl border border-[var(--fabrik-border)] bg-[var(--fabrik-card)] p-4">
      <p className="text-sm text-[var(--fabrik-muted-fg)]">${componentName}</p>
      <pre className="text-xs mt-2">{JSON.stringify(props, null, 2)}</pre>
    </div>
  )
}

export const ${name.replace(/-/g, "_")} = defineComponent({
  name: "${name.replace(/-/g, "_")}",
  description: "${componentName} component",
  schema,
  component: ${componentName}Renderer,
})
`
}
