import { existsSync, readFileSync } from "fs"
import { join } from "path"
import chalk from "chalk"

// Registry of component source (same as in add.ts)
// In a real implementation this would fetch from a remote registry
const REGISTRY: Record<string, { file: string }> = {
  card: { file: "card.tsx" },
  table: { file: "table.tsx" },
  "code-block": { file: "code-block.tsx" },
  "markdown-view": { file: "markdown-view.tsx" },
  "image-view": { file: "image-view.tsx" },
  alert: { file: "alert.tsx" },
  badge: { file: "badge.tsx" },
  tabs: { file: "tabs.tsx" },
  accordion: { file: "accordion.tsx" },
  "stat-card": { file: "stat-card.tsx" },
  "stats-grid": { file: "stats-grid.tsx" },
  "bar-chart": { file: "bar-chart.tsx" },
  "line-chart": { file: "line-chart.tsx" },
  "pie-chart": { file: "pie-chart.tsx" },
  "progress-bar": { file: "progress-bar.tsx" },
  "kpi-card": { file: "kpi-card.tsx" },
  avatar: { file: "avatar.tsx" },
  divider: { file: "divider.tsx" },
  skeleton: { file: "skeleton.tsx" },
}

export async function diff(
  component: string | undefined,
  options: { cwd?: string }
) {
  const cwd = options.cwd ?? process.cwd()

  if (!component) {
    console.log(chalk.yellow("\n  Usage: fabrik diff <component>\n"))
    console.log("  Available components:", Object.keys(REGISTRY).join(", "))
    console.log()
    return
  }

  const entry = REGISTRY[component]
  if (!entry) {
    console.log(chalk.red(`\n  Unknown component: ${component}`))
    console.log("  Available:", Object.keys(REGISTRY).join(", "))
    console.log()
    return
  }

  // Load config to find components directory
  const configPath = join(cwd, "fabrik.config.ts")
  let componentsDir = "components/fabrik"

  if (existsSync(configPath)) {
    const configContent = readFileSync(configPath, "utf-8")
    const match = configContent.match(/componentsDir:\s*"([^"]+)"/)
    if (match?.[1]) componentsDir = match[1]
  }

  const localPath = join(cwd, componentsDir, entry.file)

  if (!existsSync(localPath)) {
    console.log(chalk.red(`\n  Component not found locally: ${localPath}`))
    console.log(chalk.dim(`  Run: fabrik add ${component}\n`))
    return
  }

  const localContent = readFileSync(localPath, "utf-8")

  // Generate registry version (same generator as add.ts uses)
  const registryContent = generateRegistrySource(component)

  if (localContent === registryContent) {
    console.log(chalk.green(`\n  No changes — ${component} matches the registry version.\n`))
    return
  }

  console.log(chalk.bold(`\n  Diff for ${component} (${entry.file}):\n`))

  // Simple line-by-line diff
  const localLines = localContent.split("\n")
  const registryLines = registryContent.split("\n")
  const maxLen = Math.max(localLines.length, registryLines.length)

  let hasChanges = false

  for (let i = 0; i < maxLen; i++) {
    const local = localLines[i]
    const registry = registryLines[i]

    if (local === registry) {
      // Same line — skip in compact mode
      continue
    }

    hasChanges = true
    const lineNum = String(i + 1).padStart(4, " ")

    if (registry !== undefined && local !== undefined) {
      // Modified line
      console.log(chalk.red(`  ${lineNum} - ${registry}`))
      console.log(chalk.green(`  ${lineNum} + ${local}`))
    } else if (local !== undefined && registry === undefined) {
      // Added line
      console.log(chalk.green(`  ${lineNum} + ${local}`))
    } else if (registry !== undefined && local === undefined) {
      // Removed line
      console.log(chalk.red(`  ${lineNum} - ${registry}`))
    }
  }

  if (hasChanges) {
    console.log(
      chalk.dim(
        `\n  Local file: ${localPath}`
      )
    )
    console.log(
      chalk.dim(
        `  Lines: ${localLines.length} local, ${registryLines.length} registry\n`
      )
    )
  }
}

function generateRegistrySource(name: string): string {
  const componentName = name
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("")

  return `"use client"

import { defineComponent } from "@fabrik-sdk/ui"
import { z } from "zod"

// TODO: Implement ${componentName} component
// This is a placeholder generated by \`fabrik add ${name}\`
// Replace with your implementation

const schema = z.object({
  // Define your props here
})

function ${componentName}Renderer(props: z.infer<typeof schema>) {
  return (
    <div className="rounded-xl border border-[var(--fabrik-border)] bg-[var(--fabrik-card)] p-4">
      <p className="text-sm text-[var(--fabrik-muted-fg)]">${componentName}</p>
      <pre className="text-xs mt-2">{JSON.stringify(props, null, 2)}</pre>
    </div>
  )
}

export const ${name.replace(/-/g, "_")} = defineComponent({
  name: "${name.replace(/-/g, "_")}",
  description: "${componentName} component",
  schema,
  component: ${componentName}Renderer,
})
`
}
